// Generated by Dagger (https://dagger.dev).
package com.codinginflow.simplecachingexample.di;

import android.app.Application;
import com.codinginflow.simplecachingexample.data.RestaurantDatabase;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvideDatabaseFactory implements Factory<RestaurantDatabase> {
  private final Provider<Application> appProvider;

  public AppModule_ProvideDatabaseFactory(Provider<Application> appProvider) {
    this.appProvider = appProvider;
  }

  @Override
  public RestaurantDatabase get() {
    return provideDatabase(appProvider.get());
  }

  public static AppModule_ProvideDatabaseFactory create(Provider<Application> appProvider) {
    return new AppModule_ProvideDatabaseFactory(appProvider);
  }

  public static RestaurantDatabase provideDatabase(Application app) {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.provideDatabase(app));
  }
}
