// Generated by view binder compiler. Do not edit!
package com.codinginflow.simplecachingexample.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.codinginflow.simplecachingexample.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class RestaurantItemBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final ImageView imageViewLogo;

  @NonNull
  public final TextView textViewAddress;

  @NonNull
  public final TextView textViewName;

  @NonNull
  public final TextView textViewType;

  private RestaurantItemBinding(@NonNull RelativeLayout rootView, @NonNull ImageView imageViewLogo,
      @NonNull TextView textViewAddress, @NonNull TextView textViewName,
      @NonNull TextView textViewType) {
    this.rootView = rootView;
    this.imageViewLogo = imageViewLogo;
    this.textViewAddress = textViewAddress;
    this.textViewName = textViewName;
    this.textViewType = textViewType;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static RestaurantItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RestaurantItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.restaurant_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RestaurantItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.image_view_logo;
      ImageView imageViewLogo = rootView.findViewById(id);
      if (imageViewLogo == null) {
        break missingId;
      }

      id = R.id.text_view_address;
      TextView textViewAddress = rootView.findViewById(id);
      if (textViewAddress == null) {
        break missingId;
      }

      id = R.id.text_view_name;
      TextView textViewName = rootView.findViewById(id);
      if (textViewName == null) {
        break missingId;
      }

      id = R.id.text_view_type;
      TextView textViewType = rootView.findViewById(id);
      if (textViewType == null) {
        break missingId;
      }

      return new RestaurantItemBinding((RelativeLayout) rootView, imageViewLogo, textViewAddress,
          textViewName, textViewType);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
