// Generated by Dagger (https://dagger.dev).
package com.codinginflow.simplecachingexample.features.restaurants;

import com.codinginflow.simplecachingexample.data.RestaurantRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class RestaurantViewModel_Factory implements Factory<RestaurantViewModel> {
  private final Provider<RestaurantRepository> repositoryProvider;

  public RestaurantViewModel_Factory(Provider<RestaurantRepository> repositoryProvider) {
    this.repositoryProvider = repositoryProvider;
  }

  @Override
  public RestaurantViewModel get() {
    return newInstance(repositoryProvider.get());
  }

  public static RestaurantViewModel_Factory create(
      Provider<RestaurantRepository> repositoryProvider) {
    return new RestaurantViewModel_Factory(repositoryProvider);
  }

  public static RestaurantViewModel newInstance(RestaurantRepository repository) {
    return new RestaurantViewModel(repository);
  }
}
